# Generated by Django 2.2.1 on 2019-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_cargo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
