# Generated by Django 2.2.1 on 2019-05-24 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, help_text='Nome', max_length=100)),
                ('cpf', models.CharField(blank=True, help_text='CPF', max_length=15)),
                ('rg', models.CharField(help_text='RG', max_length=10)),
                ('data_nascimento', models.DateField()),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endereco.Endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
