# Generated by Django 2.2.1 on 2019-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=15)),
                ('bairro', models.CharField(help_text='Bairro', max_length=50)),
                ('cidade', models.CharField(help_text='Cidade', max_length=50)),
                ('uf', models.TextField(help_text='Estado', max_length=5)),
            ],
        ),
    ]
