# Generated by Django 2.2.1 on 2019-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(help_text='Estado', max_length=10),
        ),
    ]
