# Generated by Django 2.2.1 on 2019-05-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('pessoa', '0002_auto_20190524_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('salario', models.FloatField()),
                ('hora_extra', models.BigIntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(null=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo.Cargo')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
    ]
